version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: myagenda_api
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_APP=src/app.py
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/myagenda
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    command: sh -c "flask run --debug --host=0.0.0.0 --port=5000"
  db:
    image: postgres:16-alpine
    container_name: myagenda_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myagenda
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
    driver: local


