version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myagenda_api_prod
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/myagenda
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

  db:
    image: postgres:16-alpine
    container_name: myagenda_postgres_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myagenda
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata_prod:
    driver: local


