"""client uniques: drop nit unique; add phone/email unique

Revision ID: 2e904f969305
Revises: e601957d8183
Create Date: 2025-09-05 10:31:38.923190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e904f969305'
down_revision: Union[str, None] = 'e601957d8183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_nit', table_name='clients')
    op.create_index(op.f('ix_clients_nit'), 'clients', ['nit'], unique=False)
    op.create_unique_constraint(None, 'clients', ['phone'])
    op.create_unique_constraint(None, 'clients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_index(op.f('ix_clients_nit'), table_name='clients')
    op.create_index('ix_clients_nit', 'clients', ['nit'], unique=True)
    # ### end Alembic commands ###
