"""add user status enum

Revision ID: e601957d8183
Revises: 187851c2cc21
Create Date: 2025-09-05 09:55:39.835838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e601957d8183'
down_revision: Union[str, None] = '187851c2cc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = postgresql.ENUM('ACTIVE', 'INACTIVE', name='user_status', create_type=True)
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('status', postgresql.ENUM(name='user_status', create_type=False), nullable=False, server_default='ACTIVE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    status_enum = postgresql.ENUM('ACTIVE', 'INACTIVE', name='user_status')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
